<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MediaTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('media')->delete();
        
        \DB::table('media')->insert(array (
            0 => 
            array (
                'id' => 60,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 1,
                'type' => 'image',
                'file' => '/storage/media/Product/1/LFT06705.JPG',
                'thumbnail' => '/storage/media/Product/1/thumbnails/LFT06705.JPG',
                'original_name' => 'LFT06705.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 47728,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 0,
                'created_at' => '2026-02-16 14:30:24',
                'updated_at' => '2026-02-16 14:30:24',
            ),
            1 => 
            array (
                'id' => 61,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 1,
                'type' => 'image',
                'file' => '/storage/media/Product/1/LFT06706.JPG',
                'thumbnail' => '/storage/media/Product/1/thumbnails/LFT06706.JPG',
                'original_name' => 'LFT06706.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 47572,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 1,
                'created_at' => '2026-02-16 14:30:24',
                'updated_at' => '2026-02-16 14:30:24',
            ),
            2 => 
            array (
                'id' => 62,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 1,
                'type' => 'image',
                'file' => '/storage/media/Product/1/LFT06707.JPG',
                'thumbnail' => '/storage/media/Product/1/thumbnails/LFT06707.JPG',
                'original_name' => 'LFT06707.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 48096,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 2,
                'created_at' => '2026-02-16 14:30:24',
                'updated_at' => '2026-02-16 14:30:24',
            ),
            3 => 
            array (
                'id' => 63,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 1,
                'type' => 'image',
                'file' => '/storage/media/Product/1/LFT06708.JPG',
                'thumbnail' => '/storage/media/Product/1/thumbnails/LFT06708.JPG',
                'original_name' => 'LFT06708.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 47056,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 3,
                'created_at' => '2026-02-16 14:30:24',
                'updated_at' => '2026-02-16 14:30:24',
            ),
            4 => 
            array (
                'id' => 64,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 2,
                'type' => 'image',
                'file' => '/storage/media/Product/2/LFT06577.JPG',
                'thumbnail' => '/storage/media/Product/2/thumbnails/LFT06577.JPG',
                'original_name' => 'LFT06577.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 40318,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 0,
                'created_at' => '2026-02-16 14:30:25',
                'updated_at' => '2026-02-16 14:30:25',
            ),
            5 => 
            array (
                'id' => 65,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 2,
                'type' => 'image',
                'file' => '/storage/media/Product/2/LFT06663.JPG',
                'thumbnail' => '/storage/media/Product/2/thumbnails/LFT06663.JPG',
                'original_name' => 'LFT06663.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 41573,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 1,
                'created_at' => '2026-02-16 14:30:25',
                'updated_at' => '2026-02-16 14:30:25',
            ),
            6 => 
            array (
                'id' => 66,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 2,
                'type' => 'image',
                'file' => '/storage/media/Product/2/LFT06664.JPG',
                'thumbnail' => '/storage/media/Product/2/thumbnails/LFT06664.JPG',
                'original_name' => 'LFT06664.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 43268,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 2,
                'created_at' => '2026-02-16 14:30:25',
                'updated_at' => '2026-02-16 14:30:25',
            ),
            7 => 
            array (
                'id' => 67,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 2,
                'type' => 'image',
                'file' => '/storage/media/Product/2/LFT06665.JPG',
                'thumbnail' => '/storage/media/Product/2/thumbnails/LFT06665.JPG',
                'original_name' => 'LFT06665.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 44150,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 3,
                'created_at' => '2026-02-16 14:30:25',
                'updated_at' => '2026-02-16 14:30:25',
            ),
            8 => 
            array (
                'id' => 68,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 3,
                'type' => 'image',
                'file' => '/storage/media/Product/3/LFT06734.JPG',
                'thumbnail' => '/storage/media/Product/3/thumbnails/LFT06734.JPG',
                'original_name' => 'LFT06734.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 45122,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 0,
                'created_at' => '2026-02-16 14:30:25',
                'updated_at' => '2026-02-16 14:30:25',
            ),
            9 => 
            array (
                'id' => 69,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 3,
                'type' => 'image',
                'file' => '/storage/media/Product/3/LFT06735.JPG',
                'thumbnail' => '/storage/media/Product/3/thumbnails/LFT06735.JPG',
                'original_name' => 'LFT06735.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 44946,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 1,
                'created_at' => '2026-02-16 14:30:25',
                'updated_at' => '2026-02-16 14:30:25',
            ),
            10 => 
            array (
                'id' => 70,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 3,
                'type' => 'image',
                'file' => '/storage/media/Product/3/LFT06736.JPG',
                'thumbnail' => '/storage/media/Product/3/thumbnails/LFT06736.JPG',
                'original_name' => 'LFT06736.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 44230,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 2,
                'created_at' => '2026-02-16 14:30:26',
                'updated_at' => '2026-02-16 14:30:26',
            ),
            11 => 
            array (
                'id' => 71,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 3,
                'type' => 'image',
                'file' => '/storage/media/Product/3/LFT06737.JPG',
                'thumbnail' => '/storage/media/Product/3/thumbnails/LFT06737.JPG',
                'original_name' => 'LFT06737.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 45063,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 3,
                'created_at' => '2026-02-16 14:30:26',
                'updated_at' => '2026-02-16 14:30:26',
            ),
            12 => 
            array (
                'id' => 72,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 4,
                'type' => 'image',
                'file' => '/storage/media/Product/4/LFT06676.JPG',
                'thumbnail' => '/storage/media/Product/4/thumbnails/LFT06676.JPG',
                'original_name' => 'LFT06676.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 44614,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 0,
                'created_at' => '2026-02-16 14:30:26',
                'updated_at' => '2026-02-16 14:30:26',
            ),
            13 => 
            array (
                'id' => 73,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 5,
                'type' => 'image',
                'file' => '/storage/media/Product/5/LFT06709.JPG',
                'thumbnail' => '/storage/media/Product/5/thumbnails/LFT06709.JPG',
                'original_name' => 'LFT06709.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 46417,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 0,
                'created_at' => '2026-02-16 14:30:26',
                'updated_at' => '2026-02-16 14:30:26',
            ),
            14 => 
            array (
                'id' => 74,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 5,
                'type' => 'image',
                'file' => '/storage/media/Product/5/LFT06710.JPG',
                'thumbnail' => '/storage/media/Product/5/thumbnails/LFT06710.JPG',
                'original_name' => 'LFT06710.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 47149,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 1,
                'created_at' => '2026-02-16 14:30:26',
                'updated_at' => '2026-02-16 14:30:26',
            ),
            15 => 
            array (
                'id' => 75,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 6,
                'type' => 'image',
                'file' => '/storage/media/Product/6/LFT06578.JPG',
                'thumbnail' => '/storage/media/Product/6/thumbnails/LFT06578.JPG',
                'original_name' => 'LFT06578.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 38987,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 0,
                'created_at' => '2026-02-16 14:30:27',
                'updated_at' => '2026-02-16 14:30:27',
            ),
            16 => 
            array (
                'id' => 76,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 6,
                'type' => 'image',
                'file' => '/storage/media/Product/6/LFT06579.JPG',
                'thumbnail' => '/storage/media/Product/6/thumbnails/LFT06579.JPG',
                'original_name' => 'LFT06579.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 40495,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 1,
                'created_at' => '2026-02-16 14:30:27',
                'updated_at' => '2026-02-16 14:30:27',
            ),
            17 => 
            array (
                'id' => 77,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 6,
                'type' => 'image',
                'file' => '/storage/media/Product/6/LFT06580.JPG',
                'thumbnail' => '/storage/media/Product/6/thumbnails/LFT06580.JPG',
                'original_name' => 'LFT06580.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 39885,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 2,
                'created_at' => '2026-02-16 14:30:27',
                'updated_at' => '2026-02-16 14:30:27',
            ),
            18 => 
            array (
                'id' => 78,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 6,
                'type' => 'image',
                'file' => '/storage/media/Product/6/LFT06581.JPG',
                'thumbnail' => '/storage/media/Product/6/thumbnails/LFT06581.JPG',
                'original_name' => 'LFT06581.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 47001,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 3,
                'created_at' => '2026-02-16 14:30:27',
                'updated_at' => '2026-02-16 14:30:27',
            ),
            19 => 
            array (
                'id' => 79,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 7,
                'type' => 'image',
                'file' => '/storage/media/Product/7/LFT06679.JPG',
                'thumbnail' => '/storage/media/Product/7/thumbnails/LFT06679.JPG',
                'original_name' => 'LFT06679.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 45628,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 0,
                'created_at' => '2026-02-16 14:30:28',
                'updated_at' => '2026-02-16 14:30:28',
            ),
            20 => 
            array (
                'id' => 80,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 7,
                'type' => 'image',
                'file' => '/storage/media/Product/7/LFT06680.JPG',
                'thumbnail' => '/storage/media/Product/7/thumbnails/LFT06680.JPG',
                'original_name' => 'LFT06680.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 47232,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 1,
                'created_at' => '2026-02-16 14:30:28',
                'updated_at' => '2026-02-16 14:30:28',
            ),
            21 => 
            array (
                'id' => 81,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 7,
                'type' => 'image',
                'file' => '/storage/media/Product/7/LFT06681.JPG',
                'thumbnail' => '/storage/media/Product/7/thumbnails/LFT06681.JPG',
                'original_name' => 'LFT06681.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 49095,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 2,
                'created_at' => '2026-02-16 14:30:28',
                'updated_at' => '2026-02-16 14:30:28',
            ),
            22 => 
            array (
                'id' => 82,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 8,
                'type' => 'image',
                'file' => '/storage/media/Product/8/LFT06713.JPG',
                'thumbnail' => '/storage/media/Product/8/thumbnails/LFT06713.JPG',
                'original_name' => 'LFT06713.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 46641,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 0,
                'created_at' => '2026-02-16 14:30:28',
                'updated_at' => '2026-02-16 14:30:28',
            ),
            23 => 
            array (
                'id' => 83,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 8,
                'type' => 'image',
                'file' => '/storage/media/Product/8/LFT06714.JPG',
                'thumbnail' => '/storage/media/Product/8/thumbnails/LFT06714.JPG',
                'original_name' => 'LFT06714.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 47348,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 1,
                'created_at' => '2026-02-16 14:30:28',
                'updated_at' => '2026-02-16 14:30:28',
            ),
            24 => 
            array (
                'id' => 84,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 9,
                'type' => 'image',
                'file' => '/storage/media/Product/9/LFT06585.JPG',
                'thumbnail' => '/storage/media/Product/9/thumbnails/LFT06585.JPG',
                'original_name' => 'LFT06585.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 47871,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 0,
                'created_at' => '2026-02-16 14:30:29',
                'updated_at' => '2026-02-16 14:30:29',
            ),
            25 => 
            array (
                'id' => 85,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 9,
                'type' => 'image',
                'file' => '/storage/media/Product/9/LFT06586.JPG',
                'thumbnail' => '/storage/media/Product/9/thumbnails/LFT06586.JPG',
                'original_name' => 'LFT06586.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 47592,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 1,
                'created_at' => '2026-02-16 14:30:29',
                'updated_at' => '2026-02-16 14:30:29',
            ),
            26 => 
            array (
                'id' => 86,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 10,
                'type' => 'image',
                'file' => '/storage/media/Product/10/LFT06684.JPG',
                'thumbnail' => '/storage/media/Product/10/thumbnails/LFT06684.JPG',
                'original_name' => 'LFT06684.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 48037,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 0,
                'created_at' => '2026-02-16 14:30:29',
                'updated_at' => '2026-02-16 14:30:29',
            ),
            27 => 
            array (
                'id' => 87,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 10,
                'type' => 'image',
                'file' => '/storage/media/Product/10/LFT06685.JPG',
                'thumbnail' => '/storage/media/Product/10/thumbnails/LFT06685.JPG',
                'original_name' => 'LFT06685.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 50876,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 1,
                'created_at' => '2026-02-16 14:30:29',
                'updated_at' => '2026-02-16 14:30:29',
            ),
            28 => 
            array (
                'id' => 88,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 11,
                'type' => 'image',
                'file' => '/storage/media/Product/11/LFT06715.JPG',
                'thumbnail' => '/storage/media/Product/11/thumbnails/LFT06715.JPG',
                'original_name' => 'LFT06715.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 47978,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 0,
                'created_at' => '2026-02-16 14:30:29',
                'updated_at' => '2026-02-16 14:30:29',
            ),
            29 => 
            array (
                'id' => 89,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 11,
                'type' => 'image',
                'file' => '/storage/media/Product/11/LFT06716.JPG',
                'thumbnail' => '/storage/media/Product/11/thumbnails/LFT06716.JPG',
                'original_name' => 'LFT06716.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 48495,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 1,
                'created_at' => '2026-02-16 14:30:30',
                'updated_at' => '2026-02-16 14:30:30',
            ),
            30 => 
            array (
                'id' => 90,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 12,
                'type' => 'image',
                'file' => '/storage/media/Product/12/LFT06587.JPG',
                'thumbnail' => '/storage/media/Product/12/thumbnails/LFT06587.JPG',
                'original_name' => 'LFT06587.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 46880,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 0,
                'created_at' => '2026-02-16 14:30:30',
                'updated_at' => '2026-02-16 14:30:30',
            ),
            31 => 
            array (
                'id' => 91,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 12,
                'type' => 'image',
                'file' => '/storage/media/Product/12/LFT06588.JPG',
                'thumbnail' => '/storage/media/Product/12/thumbnails/LFT06588.JPG',
                'original_name' => 'LFT06588.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 42161,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 1,
                'created_at' => '2026-02-16 14:30:30',
                'updated_at' => '2026-02-16 14:30:30',
            ),
            32 => 
            array (
                'id' => 92,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 12,
                'type' => 'image',
                'file' => '/storage/media/Product/12/LFT06589.JPG',
                'thumbnail' => '/storage/media/Product/12/thumbnails/LFT06589.JPG',
                'original_name' => 'LFT06589.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 48266,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 2,
                'created_at' => '2026-02-16 14:30:30',
                'updated_at' => '2026-02-16 14:30:30',
            ),
            33 => 
            array (
                'id' => 93,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 13,
                'type' => 'image',
                'file' => '/storage/media/Product/13/LFT06717.JPG',
                'thumbnail' => '/storage/media/Product/13/thumbnails/LFT06717.JPG',
                'original_name' => 'LFT06717.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 46289,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 0,
                'created_at' => '2026-02-16 14:30:30',
                'updated_at' => '2026-02-16 14:30:30',
            ),
            34 => 
            array (
                'id' => 94,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 13,
                'type' => 'image',
                'file' => '/storage/media/Product/13/LFT06718.JPG',
                'thumbnail' => '/storage/media/Product/13/thumbnails/LFT06718.JPG',
                'original_name' => 'LFT06718.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 47080,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 1,
                'created_at' => '2026-02-16 14:30:31',
                'updated_at' => '2026-02-16 14:30:31',
            ),
            35 => 
            array (
                'id' => 95,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 14,
                'type' => 'image',
                'file' => '/storage/media/Product/14/LFT06590.JPG',
                'thumbnail' => '/storage/media/Product/14/thumbnails/LFT06590.JPG',
                'original_name' => 'LFT06590.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 40827,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 0,
                'created_at' => '2026-02-16 14:30:31',
                'updated_at' => '2026-02-16 14:30:31',
            ),
            36 => 
            array (
                'id' => 96,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 14,
                'type' => 'image',
                'file' => '/storage/media/Product/14/LFT06591.JPG',
                'thumbnail' => '/storage/media/Product/14/thumbnails/LFT06591.JPG',
                'original_name' => 'LFT06591.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 40884,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 1,
                'created_at' => '2026-02-16 14:30:31',
                'updated_at' => '2026-02-16 14:30:31',
            ),
            37 => 
            array (
                'id' => 97,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 14,
                'type' => 'image',
                'file' => '/storage/media/Product/14/LFT06592.JPG',
                'thumbnail' => '/storage/media/Product/14/thumbnails/LFT06592.JPG',
                'original_name' => 'LFT06592.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 45112,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 2,
                'created_at' => '2026-02-16 14:30:31',
                'updated_at' => '2026-02-16 14:30:31',
            ),
            38 => 
            array (
                'id' => 98,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 14,
                'type' => 'image',
                'file' => '/storage/media/Product/14/LFT06593.JPG',
                'thumbnail' => '/storage/media/Product/14/thumbnails/LFT06593.JPG',
                'original_name' => 'LFT06593.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 44639,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 3,
                'created_at' => '2026-02-16 14:30:31',
                'updated_at' => '2026-02-16 14:30:31',
            ),
            39 => 
            array (
                'id' => 99,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 15,
                'type' => 'image',
                'file' => '/storage/media/Product/15/LFT06719.JPG',
                'thumbnail' => '/storage/media/Product/15/thumbnails/LFT06719.JPG',
                'original_name' => 'LFT06719.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 45935,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 0,
                'created_at' => '2026-02-16 14:30:32',
                'updated_at' => '2026-02-16 14:30:32',
            ),
            40 => 
            array (
                'id' => 100,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 15,
                'type' => 'image',
                'file' => '/storage/media/Product/15/LFT06720.JPG',
                'thumbnail' => '/storage/media/Product/15/thumbnails/LFT06720.JPG',
                'original_name' => 'LFT06720.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 46822,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 1,
                'created_at' => '2026-02-16 14:30:32',
                'updated_at' => '2026-02-16 14:30:32',
            ),
            41 => 
            array (
                'id' => 101,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 16,
                'type' => 'image',
                'file' => '/storage/media/Product/16/LFT06594.JPG',
                'thumbnail' => '/storage/media/Product/16/thumbnails/LFT06594.JPG',
                'original_name' => 'LFT06594.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 43476,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 0,
                'created_at' => '2026-02-16 14:30:32',
                'updated_at' => '2026-02-16 14:30:32',
            ),
            42 => 
            array (
                'id' => 102,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 16,
                'type' => 'image',
                'file' => '/storage/media/Product/16/LFT06595.JPG',
                'thumbnail' => '/storage/media/Product/16/thumbnails/LFT06595.JPG',
                'original_name' => 'LFT06595.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 43955,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 1,
                'created_at' => '2026-02-16 14:30:32',
                'updated_at' => '2026-02-16 14:30:32',
            ),
            43 => 
            array (
                'id' => 103,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 17,
                'type' => 'image',
                'file' => '/storage/media/Product/17/LFT06596.JPG',
                'thumbnail' => '/storage/media/Product/17/thumbnails/LFT06596.JPG',
                'original_name' => 'LFT06596.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 44724,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 0,
                'created_at' => '2026-02-16 14:30:32',
                'updated_at' => '2026-02-16 14:30:32',
            ),
            44 => 
            array (
                'id' => 104,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 17,
                'type' => 'image',
                'file' => '/storage/media/Product/17/LFT06597.JPG',
                'thumbnail' => '/storage/media/Product/17/thumbnails/LFT06597.JPG',
                'original_name' => 'LFT06597.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 46347,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 1,
                'created_at' => '2026-02-16 14:30:33',
                'updated_at' => '2026-02-16 14:30:33',
            ),
            45 => 
            array (
                'id' => 105,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 18,
                'type' => 'image',
                'file' => '/storage/media/Product/18/LFT06725.JPG',
                'thumbnail' => '/storage/media/Product/18/thumbnails/LFT06725.JPG',
                'original_name' => 'LFT06725.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 47904,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 0,
                'created_at' => '2026-02-16 14:30:33',
                'updated_at' => '2026-02-16 14:30:33',
            ),
            46 => 
            array (
                'id' => 106,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 18,
                'type' => 'image',
                'file' => '/storage/media/Product/18/LFT06726.JPG',
                'thumbnail' => '/storage/media/Product/18/thumbnails/LFT06726.JPG',
                'original_name' => 'LFT06726.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 49006,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 1,
                'created_at' => '2026-02-16 14:30:33',
                'updated_at' => '2026-02-16 14:30:33',
            ),
            47 => 
            array (
                'id' => 107,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 19,
                'type' => 'image',
                'file' => '/storage/media/Product/19/LFT06598.JPG',
                'thumbnail' => '/storage/media/Product/19/thumbnails/LFT06598.JPG',
                'original_name' => 'LFT06598.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 46300,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 0,
                'created_at' => '2026-02-16 14:30:33',
                'updated_at' => '2026-02-16 14:30:33',
            ),
            48 => 
            array (
                'id' => 108,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 19,
                'type' => 'image',
                'file' => '/storage/media/Product/19/LFT06599.JPG',
                'thumbnail' => '/storage/media/Product/19/thumbnails/LFT06599.JPG',
                'original_name' => 'LFT06599.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 46013,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 1,
                'created_at' => '2026-02-16 14:30:33',
                'updated_at' => '2026-02-16 14:30:33',
            ),
            49 => 
            array (
                'id' => 109,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 19,
                'type' => 'image',
                'file' => '/storage/media/Product/19/LFT06600.JPG',
                'thumbnail' => '/storage/media/Product/19/thumbnails/LFT06600.JPG',
                'original_name' => 'LFT06600.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 46582,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 2,
                'created_at' => '2026-02-16 14:30:34',
                'updated_at' => '2026-02-16 14:30:34',
            ),
            50 => 
            array (
                'id' => 110,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 19,
                'type' => 'image',
                'file' => '/storage/media/Product/19/LFT06601.JPG',
                'thumbnail' => '/storage/media/Product/19/thumbnails/LFT06601.JPG',
                'original_name' => 'LFT06601.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 43838,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 3,
                'created_at' => '2026-02-16 14:30:34',
                'updated_at' => '2026-02-16 14:30:34',
            ),
            51 => 
            array (
                'id' => 111,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 19,
                'type' => 'image',
                'file' => '/storage/media/Product/19/LFT06602.JPG',
                'thumbnail' => '/storage/media/Product/19/thumbnails/LFT06602.JPG',
                'original_name' => 'LFT06602.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 44814,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 4,
                'created_at' => '2026-02-16 14:30:34',
                'updated_at' => '2026-02-16 14:30:34',
            ),
            52 => 
            array (
                'id' => 112,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 19,
                'type' => 'image',
                'file' => '/storage/media/Product/19/LFT06603.JPG',
                'thumbnail' => '/storage/media/Product/19/thumbnails/LFT06603.JPG',
                'original_name' => 'LFT06603.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 44741,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 5,
                'created_at' => '2026-02-16 14:30:34',
                'updated_at' => '2026-02-16 14:30:34',
            ),
            53 => 
            array (
                'id' => 113,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 19,
                'type' => 'image',
                'file' => '/storage/media/Product/19/LFT06604.JPG',
                'thumbnail' => '/storage/media/Product/19/thumbnails/LFT06604.JPG',
                'original_name' => 'LFT06604.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 45916,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 6,
                'created_at' => '2026-02-16 14:30:34',
                'updated_at' => '2026-02-16 14:30:34',
            ),
            54 => 
            array (
                'id' => 114,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 20,
                'type' => 'image',
                'file' => '/storage/media/Product/20/LFT06727.JPG',
                'thumbnail' => '/storage/media/Product/20/thumbnails/LFT06727.JPG',
                'original_name' => 'LFT06727.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 45284,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 0,
                'created_at' => '2026-02-16 14:30:34',
                'updated_at' => '2026-02-16 14:30:34',
            ),
            55 => 
            array (
                'id' => 115,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 20,
                'type' => 'image',
                'file' => '/storage/media/Product/20/LFT06728.JPG',
                'thumbnail' => '/storage/media/Product/20/thumbnails/LFT06728.JPG',
                'original_name' => 'LFT06728.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 46628,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 1,
                'created_at' => '2026-02-16 14:30:35',
                'updated_at' => '2026-02-16 14:30:35',
            ),
            56 => 
            array (
                'id' => 116,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 20,
                'type' => 'image',
                'file' => '/storage/media/Product/20/LFT06729.JPG',
                'thumbnail' => '/storage/media/Product/20/thumbnails/LFT06729.JPG',
                'original_name' => 'LFT06729.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 48280,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 2,
                'created_at' => '2026-02-16 14:30:35',
                'updated_at' => '2026-02-16 14:30:35',
            ),
            57 => 
            array (
                'id' => 117,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 21,
                'type' => 'image',
                'file' => '/storage/media/Product/21/LFT06605.JPG',
                'thumbnail' => '/storage/media/Product/21/thumbnails/LFT06605.JPG',
                'original_name' => 'LFT06605.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 45368,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 0,
                'created_at' => '2026-02-16 14:30:35',
                'updated_at' => '2026-02-16 14:30:35',
            ),
            58 => 
            array (
                'id' => 118,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 21,
                'type' => 'image',
                'file' => '/storage/media/Product/21/LFT06606.JPG',
                'thumbnail' => '/storage/media/Product/21/thumbnails/LFT06606.JPG',
                'original_name' => 'LFT06606.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 46523,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 1,
                'created_at' => '2026-02-16 14:30:35',
                'updated_at' => '2026-02-16 14:30:35',
            ),
            59 => 
            array (
                'id' => 119,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 22,
                'type' => 'image',
                'file' => '/storage/media/Product/22/LFT06608.JPG',
                'thumbnail' => '/storage/media/Product/22/thumbnails/LFT06608.JPG',
                'original_name' => 'LFT06608.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 48620,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 0,
                'created_at' => '2026-02-16 14:30:35',
                'updated_at' => '2026-02-16 14:30:35',
            ),
            60 => 
            array (
                'id' => 120,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 23,
                'type' => 'image',
                'file' => '/storage/media/Product/23/LFT06730.JPG',
                'thumbnail' => '/storage/media/Product/23/thumbnails/LFT06730.JPG',
                'original_name' => 'LFT06730.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 47697,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 0,
                'created_at' => '2026-02-16 14:30:36',
                'updated_at' => '2026-02-16 14:30:36',
            ),
            61 => 
            array (
                'id' => 121,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 23,
                'type' => 'image',
                'file' => '/storage/media/Product/23/LFT06731.JPG',
                'thumbnail' => '/storage/media/Product/23/thumbnails/LFT06731.JPG',
                'original_name' => 'LFT06731.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 48310,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 1,
                'created_at' => '2026-02-16 14:30:36',
                'updated_at' => '2026-02-16 14:30:36',
            ),
            62 => 
            array (
                'id' => 122,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 24,
                'type' => 'image',
                'file' => '/storage/media/Product/24/LFT06612.JPG',
                'thumbnail' => '/storage/media/Product/24/thumbnails/LFT06612.JPG',
                'original_name' => 'LFT06612.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 48076,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 0,
                'created_at' => '2026-02-16 14:30:36',
                'updated_at' => '2026-02-16 14:30:36',
            ),
            63 => 
            array (
                'id' => 123,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 25,
                'type' => 'image',
                'file' => '/storage/media/Product/25/LFT06614.JPG',
                'thumbnail' => '/storage/media/Product/25/thumbnails/LFT06614.JPG',
                'original_name' => 'LFT06614.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 48123,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 0,
                'created_at' => '2026-02-16 14:30:36',
                'updated_at' => '2026-02-16 14:30:36',
            ),
            64 => 
            array (
                'id' => 124,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 25,
                'type' => 'image',
                'file' => '/storage/media/Product/25/LFT06615.JPG',
                'thumbnail' => '/storage/media/Product/25/thumbnails/LFT06615.JPG',
                'original_name' => 'LFT06615.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 45195,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 1,
                'created_at' => '2026-02-16 14:30:37',
                'updated_at' => '2026-02-16 14:30:37',
            ),
            65 => 
            array (
                'id' => 125,
                'mediable_type' => 'App\\Models\\Product',
                'mediable_id' => 25,
                'type' => 'image',
                'file' => '/storage/media/Product/25/LFT06616.JPG',
                'thumbnail' => '/storage/media/Product/25/thumbnails/LFT06616.JPG',
                'original_name' => 'LFT06616.JPG',
                'mime_type' => 'image/jpeg',
                'size' => 48705,
                'width' => 1080,
                'height' => 720,
                'sort_order' => 2,
                'created_at' => '2026-02-16 14:30:37',
                'updated_at' => '2026-02-16 14:30:37',
            ),
        ));
        
        
    }
}