<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('products')->delete();
        
        \DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 1,
                'sku' => 'CAM-005',
                'category_id' => 4,
                'brand_id' => 7,
                'is_active' => 1,
                'is_featured' => 1,
                'sort_order' => 37,
                'name' => 'Gucci Cam-005',
                'text' => 'Descubre los Gucci Cam-005, una perfecta combinación de estilo y funcionalidad. Fabricado con los mejores materiales para garantizar confort y durabilidad.',
                'price' => '1419872.00',
                'list_price' => '1774840.00',
                'slug' => 'gucci-02-cam-005',
                'icon' => NULL,
                'description' => 'Gucci Cam-005 - Elegante y moderno diseño con materiales de alta calidad. Ideal para cualquier ocasión.',
                'specifications' => NULL,
                'active' => 1,
                'order' => 0,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-16 14:30:22',
                'updated_at' => '2026-02-16 14:30:22',
            ),
            1 => 
            array (
                'id' => 2,
                'sku' => 'CAM-015',
                'category_id' => 1,
                'brand_id' => 7,
                'is_active' => 1,
                'is_featured' => 0,
                'sort_order' => 31,
                'name' => 'Gucci Cam-015',
                'text' => 'Descubre los Gucci Cam-015, una perfecta combinación de estilo y funcionalidad. Fabricado con los mejores materiales para garantizar confort y durabilidad.',
                'price' => '1251994.00',
                'list_price' => '1564992.50',
                'slug' => 'gucci-02-cam-015',
                'icon' => NULL,
                'description' => 'Gucci Cam-015 - Elegante y moderno diseño con materiales de alta calidad. Ideal para cualquier ocasión.',
                'specifications' => NULL,
                'active' => 1,
                'order' => 0,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-16 14:30:24',
                'updated_at' => '2026-02-16 14:30:24',
            ),
            2 => 
            array (
                'id' => 3,
                'sku' => 'CAM-016',
                'category_id' => 3,
                'brand_id' => 7,
                'is_active' => 1,
                'is_featured' => 0,
                'sort_order' => 38,
                'name' => 'Gucci Cam-016',
                'text' => 'Descubre los Gucci Cam-016, una perfecta combinación de estilo y funcionalidad. Fabricado con los mejores materiales para garantizar confort y durabilidad.',
                'price' => '1268464.00',
                'list_price' => '1585580.00',
                'slug' => 'gucci-02-cam-016',
                'icon' => NULL,
                'description' => 'Gucci Cam-016 - Elegante y moderno diseño con materiales de alta calidad. Ideal para cualquier ocasión.',
                'specifications' => NULL,
                'active' => 1,
                'order' => 0,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-16 14:30:25',
                'updated_at' => '2026-02-16 14:30:25',
            ),
            3 => 
            array (
                'id' => 4,
                'sku' => 'CAM-001',
                'category_id' => 4,
                'brand_id' => 8,
                'is_active' => 1,
                'is_featured' => 0,
                'sort_order' => 86,
                'name' => 'Dior Cam-001',
                'text' => 'Descubre los Dior Cam-001, una perfecta combinación de estilo y funcionalidad. Fabricado con los mejores materiales para garantizar confort y durabilidad.',
                'price' => '939762.00',
                'list_price' => '1174702.50',
                'slug' => 'dior-03-cam-001',
                'icon' => NULL,
                'description' => 'Dior Cam-001 - Elegante y moderno diseño con materiales de alta calidad. Ideal para cualquier ocasión.',
                'specifications' => NULL,
                'active' => 1,
                'order' => 0,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-16 14:30:26',
                'updated_at' => '2026-02-16 14:30:26',
            ),
            4 => 
            array (
                'id' => 5,
                'sku' => 'CAM-005',
                'category_id' => 4,
                'brand_id' => 4,
                'is_active' => 1,
                'is_featured' => 0,
                'sort_order' => 73,
                'name' => 'Target Cam-005',
                'text' => 'Descubre los Target Cam-005, una perfecta combinación de estilo y funcionalidad. Fabricado con los mejores materiales para garantizar confort y durabilidad.',
                'price' => '412973.00',
                'list_price' => '516216.25',
                'slug' => 'target-03-cam-005',
                'icon' => NULL,
                'description' => 'Target Cam-005 - Elegante y moderno diseño con materiales de alta calidad. Ideal para cualquier ocasión.',
                'specifications' => NULL,
                'active' => 1,
                'order' => 0,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-16 14:30:26',
                'updated_at' => '2026-02-16 14:30:26',
            ),
            5 => 
            array (
                'id' => 6,
                'sku' => 'CAM-015',
                'category_id' => 4,
                'brand_id' => 1,
                'is_active' => 1,
                'is_featured' => 0,
                'sort_order' => 63,
                'name' => 'Ray-Ban Cam-015',
                'text' => 'Descubre los Ray-Ban Cam-015, una perfecta combinación de estilo y funcionalidad. Fabricado con los mejores materiales para garantizar confort y durabilidad.',
                'price' => '768420.00',
                'list_price' => '960525.00',
                'slug' => 'ray-ban-03-cam-015',
                'icon' => NULL,
                'description' => 'Ray-Ban Cam-015 - Elegante y moderno diseño con materiales de alta calidad. Ideal para cualquier ocasión.',
                'specifications' => NULL,
                'active' => 1,
                'order' => 0,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-16 14:30:26',
                'updated_at' => '2026-02-16 14:30:26',
            ),
            6 => 
            array (
                'id' => 7,
                'sku' => 'CAM-001',
                'category_id' => 3,
                'brand_id' => 1,
                'is_active' => 1,
                'is_featured' => 0,
                'sort_order' => 99,
                'name' => 'Ray-Ban Cam-001',
                'text' => 'Descubre los Ray-Ban Cam-001, una perfecta combinación de estilo y funcionalidad. Fabricado con los mejores materiales para garantizar confort y durabilidad.',
                'price' => '584791.00',
                'list_price' => '730988.75',
                'slug' => 'ray-ban-04-cam-001',
                'icon' => NULL,
                'description' => 'Ray-Ban Cam-001 - Elegante y moderno diseño con materiales de alta calidad. Ideal para cualquier ocasión.',
                'specifications' => NULL,
                'active' => 1,
                'order' => 0,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-16 14:30:27',
                'updated_at' => '2026-02-16 14:30:27',
            ),
            7 => 
            array (
                'id' => 8,
                'sku' => 'CAM-006',
                'category_id' => 1,
                'brand_id' => 7,
                'is_active' => 1,
                'is_featured' => 0,
                'sort_order' => 87,
                'name' => 'Gucci Cam-006',
                'text' => 'Descubre los Gucci Cam-006, una perfecta combinación de estilo y funcionalidad. Fabricado con los mejores materiales para garantizar confort y durabilidad.',
                'price' => '1584885.00',
                'list_price' => '1981106.25',
                'slug' => 'gucci-05-cam-006',
                'icon' => NULL,
                'description' => 'Gucci Cam-006 - Elegante y moderno diseño con materiales de alta calidad. Ideal para cualquier ocasión.',
                'specifications' => NULL,
                'active' => 1,
                'order' => 0,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-16 14:30:28',
                'updated_at' => '2026-02-16 14:30:28',
            ),
            8 => 
            array (
                'id' => 9,
                'sku' => 'CAM-008',
                'category_id' => 1,
                'brand_id' => 1,
                'is_active' => 1,
                'is_featured' => 0,
                'sort_order' => 78,
                'name' => 'Ray-Ban Cam-008',
                'text' => 'Descubre los Ray-Ban Cam-008, una perfecta combinación de estilo y funcionalidad. Fabricado con los mejores materiales para garantizar confort y durabilidad.',
                'price' => '629453.00',
                'list_price' => '786816.25',
                'slug' => 'ray-ban-05-cam-008',
                'icon' => NULL,
                'description' => 'Ray-Ban Cam-008 - Elegante y moderno diseño con materiales de alta calidad. Ideal para cualquier ocasión.',
                'specifications' => NULL,
                'active' => 1,
                'order' => 0,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-16 14:30:28',
                'updated_at' => '2026-02-16 14:30:28',
            ),
            9 => 
            array (
                'id' => 10,
                'sku' => 'CAM-002',
                'category_id' => 1,
                'brand_id' => 7,
                'is_active' => 1,
                'is_featured' => 1,
                'sort_order' => 98,
                'name' => 'Gucci Cam-002',
                'text' => 'Descubre los Gucci Cam-002, una perfecta combinación de estilo y funcionalidad. Fabricado con los mejores materiales para garantizar confort y durabilidad.',
                'price' => '1724472.00',
                'list_price' => '2155590.00',
                'slug' => 'gucci-06-cam-002',
                'icon' => NULL,
                'description' => 'Gucci Cam-002 - Elegante y moderno diseño con materiales de alta calidad. Ideal para cualquier ocasión.',
                'specifications' => NULL,
                'active' => 1,
                'order' => 0,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-16 14:30:29',
                'updated_at' => '2026-02-16 14:30:29',
            ),
            10 => 
            array (
                'id' => 11,
                'sku' => 'CAM-006',
                'category_id' => 1,
                'brand_id' => 4,
                'is_active' => 1,
                'is_featured' => 0,
                'sort_order' => 24,
                'name' => 'Target Cam-006',
                'text' => 'Descubre los Target Cam-006, una perfecta combinación de estilo y funcionalidad. Fabricado con los mejores materiales para garantizar confort y durabilidad.',
                'price' => '421635.00',
                'list_price' => '527043.75',
                'slug' => 'target-06-cam-006',
                'icon' => NULL,
                'description' => 'Target Cam-006 - Elegante y moderno diseño con materiales de alta calidad. Ideal para cualquier ocasión.',
                'specifications' => NULL,
                'active' => 1,
                'order' => 0,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-16 14:30:29',
                'updated_at' => '2026-02-16 14:30:29',
            ),
            11 => 
            array (
                'id' => 12,
                'sku' => 'CAM-008',
                'category_id' => 1,
                'brand_id' => 3,
                'is_active' => 1,
                'is_featured' => 0,
                'sort_order' => 99,
                'name' => 'Vogue Cam-008',
                'text' => 'Descubre los Vogue Cam-008, una perfecta combinación de estilo y funcionalidad. Fabricado con los mejores materiales para garantizar confort y durabilidad.',
                'price' => '613945.00',
                'list_price' => '767431.25',
                'slug' => 'vogue-06-cam-008',
                'icon' => NULL,
                'description' => 'Vogue Cam-008 - Elegante y moderno diseño con materiales de alta calidad. Ideal para cualquier ocasión.',
                'specifications' => NULL,
                'active' => 1,
                'order' => 0,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-16 14:30:30',
                'updated_at' => '2026-02-16 14:30:30',
            ),
            12 => 
            array (
                'id' => 13,
                'sku' => 'CAM-006',
                'category_id' => 1,
                'brand_id' => 4,
                'is_active' => 1,
                'is_featured' => 0,
                'sort_order' => 14,
                'name' => 'Target Cam-006',
                'text' => 'Descubre los Target Cam-006, una perfecta combinación de estilo y funcionalidad. Fabricado con los mejores materiales para garantizar confort y durabilidad.',
                'price' => '402217.00',
                'list_price' => '502771.25',
                'slug' => 'target-07-cam-006',
                'icon' => NULL,
                'description' => 'Target Cam-006 - Elegante y moderno diseño con materiales de alta calidad. Ideal para cualquier ocasión.',
                'specifications' => NULL,
                'active' => 1,
                'order' => 0,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-16 14:30:30',
                'updated_at' => '2026-02-16 14:30:30',
            ),
            13 => 
            array (
                'id' => 14,
                'sku' => 'CAM-008',
                'category_id' => 2,
                'brand_id' => 8,
                'is_active' => 1,
                'is_featured' => 0,
                'sort_order' => 19,
                'name' => 'Dior Cam-008',
                'text' => 'Descubre los Dior Cam-008, una perfecta combinación de estilo y funcionalidad. Fabricado con los mejores materiales para garantizar confort y durabilidad.',
                'price' => '1178652.00',
                'list_price' => '1473315.00',
                'slug' => 'dior-07-cam-008',
                'icon' => NULL,
                'description' => 'Dior Cam-008 - Elegante y moderno diseño con materiales de alta calidad. Ideal para cualquier ocasión.',
                'specifications' => NULL,
                'active' => 1,
                'order' => 0,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-16 14:30:31',
                'updated_at' => '2026-02-16 14:30:31',
            ),
            14 => 
            array (
                'id' => 15,
                'sku' => 'CAM-006',
                'category_id' => 2,
                'brand_id' => 4,
                'is_active' => 1,
                'is_featured' => 0,
                'sort_order' => 78,
                'name' => 'Target Cam-006',
                'text' => 'Descubre los Target Cam-006, una perfecta combinación de estilo y funcionalidad. Fabricado con los mejores materiales para garantizar confort y durabilidad.',
                'price' => '497786.00',
                'list_price' => '622232.50',
                'slug' => 'target-08-cam-006',
                'icon' => NULL,
                'description' => 'Target Cam-006 - Elegante y moderno diseño con materiales de alta calidad. Ideal para cualquier ocasión.',
                'specifications' => NULL,
                'active' => 1,
                'order' => 0,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-16 14:30:31',
                'updated_at' => '2026-02-16 14:30:31',
            ),
            15 => 
            array (
                'id' => 16,
                'sku' => 'CAM-009',
                'category_id' => 2,
                'brand_id' => 10,
                'is_active' => 1,
                'is_featured' => 0,
                'sort_order' => 9,
                'name' => 'Tom Ford Cam-009',
                'text' => 'Descubre los Tom Ford Cam-009, una perfecta combinación de estilo y funcionalidad. Fabricado con los mejores materiales para garantizar confort y durabilidad.',
                'price' => '561159.00',
                'list_price' => '701448.75',
                'slug' => 'tom-ford-08-cam-009',
                'icon' => NULL,
                'description' => 'Tom Ford Cam-009 - Elegante y moderno diseño con materiales de alta calidad. Ideal para cualquier ocasión.',
                'specifications' => NULL,
                'active' => 1,
                'order' => 0,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-16 14:30:32',
                'updated_at' => '2026-02-16 14:30:32',
            ),
            16 => 
            array (
                'id' => 17,
                'sku' => 'CAM-009',
                'category_id' => 1,
                'brand_id' => 1,
                'is_active' => 1,
                'is_featured' => 0,
                'sort_order' => 59,
                'name' => 'Ray-Ban Cam-009',
                'text' => 'Descubre los Ray-Ban Cam-009, una perfecta combinación de estilo y funcionalidad. Fabricado con los mejores materiales para garantizar confort y durabilidad.',
                'price' => '608073.00',
                'list_price' => '760091.25',
                'slug' => 'ray-ban-09-cam-009',
                'icon' => NULL,
                'description' => 'Ray-Ban Cam-009 - Elegante y moderno diseño con materiales de alta calidad. Ideal para cualquier ocasión.',
                'specifications' => NULL,
                'active' => 1,
                'order' => 0,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-16 14:30:32',
                'updated_at' => '2026-02-16 14:30:32',
            ),
            17 => 
            array (
                'id' => 18,
                'sku' => 'CAM-004',
                'category_id' => 3,
                'brand_id' => 9,
                'is_active' => 1,
                'is_featured' => 0,
                'sort_order' => 41,
                'name' => 'Chanel Cam-004',
                'text' => 'Descubre los Chanel Cam-004, una perfecta combinación de estilo y funcionalidad. Fabricado con los mejores materiales para garantizar confort y durabilidad.',
                'price' => '1251259.00',
                'list_price' => '1564073.75',
                'slug' => 'chanel-10-cam-004',
                'icon' => NULL,
                'description' => 'Chanel Cam-004 - Elegante y moderno diseño con materiales de alta calidad. Ideal para cualquier ocasión.',
                'specifications' => NULL,
                'active' => 1,
                'order' => 0,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-16 14:30:33',
                'updated_at' => '2026-02-16 14:30:33',
            ),
            18 => 
            array (
                'id' => 19,
                'sku' => 'CAM-009',
                'category_id' => 2,
                'brand_id' => 1,
                'is_active' => 1,
                'is_featured' => 0,
                'sort_order' => 86,
                'name' => 'Ray-Ban Cam-009',
                'text' => 'Descubre los Ray-Ban Cam-009, una perfecta combinación de estilo y funcionalidad. Fabricado con los mejores materiales para garantizar confort y durabilidad.',
                'price' => '818945.00',
                'list_price' => '1023681.25',
                'slug' => 'ray-ban-10-cam-009',
                'icon' => NULL,
                'description' => 'Ray-Ban Cam-009 - Elegante y moderno diseño con materiales de alta calidad. Ideal para cualquier ocasión.',
                'specifications' => NULL,
                'active' => 1,
                'order' => 0,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-16 14:30:33',
                'updated_at' => '2026-02-16 14:30:33',
            ),
            19 => 
            array (
                'id' => 20,
                'sku' => 'CAM-004',
                'category_id' => 2,
                'brand_id' => 4,
                'is_active' => 1,
                'is_featured' => 1,
                'sort_order' => 28,
                'name' => 'Target Cam-004',
                'text' => 'Descubre los Target Cam-004, una perfecta combinación de estilo y funcionalidad. Fabricado con los mejores materiales para garantizar confort y durabilidad.',
                'price' => '419350.00',
                'list_price' => '524187.50',
                'slug' => 'target-11-cam-004',
                'icon' => NULL,
                'description' => 'Target Cam-004 - Elegante y moderno diseño con materiales de alta calidad. Ideal para cualquier ocasión.',
                'specifications' => NULL,
                'active' => 1,
                'order' => 0,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-16 14:30:34',
                'updated_at' => '2026-02-16 14:30:34',
            ),
            20 => 
            array (
                'id' => 21,
                'sku' => 'CAM-009',
                'category_id' => 3,
                'brand_id' => 8,
                'is_active' => 1,
                'is_featured' => 0,
                'sort_order' => 70,
                'name' => 'Dior Cam-009',
                'text' => 'Descubre los Dior Cam-009, una perfecta combinación de estilo y funcionalidad. Fabricado con los mejores materiales para garantizar confort y durabilidad.',
                'price' => '1032327.00',
                'list_price' => '1290408.75',
                'slug' => 'dior-11-cam-009',
                'icon' => NULL,
                'description' => 'Dior Cam-009 - Elegante y moderno diseño con materiales de alta calidad. Ideal para cualquier ocasión.',
                'specifications' => NULL,
                'active' => 1,
                'order' => 0,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-16 14:30:35',
                'updated_at' => '2026-02-16 14:30:35',
            ),
            21 => 
            array (
                'id' => 22,
                'sku' => 'CAM-007',
                'category_id' => 3,
                'brand_id' => 4,
                'is_active' => 1,
                'is_featured' => 0,
                'sort_order' => 47,
                'name' => 'Target Cam-007',
                'text' => 'Descubre los Target Cam-007, una perfecta combinación de estilo y funcionalidad. Fabricado con los mejores materiales para garantizar confort y durabilidad.',
                'price' => '377711.00',
                'list_price' => '472138.75',
                'slug' => 'target-12-cam-007',
                'icon' => NULL,
                'description' => 'Target Cam-007 - Elegante y moderno diseño con materiales de alta calidad. Ideal para cualquier ocasión.',
                'specifications' => NULL,
                'active' => 1,
                'order' => 0,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-16 14:30:35',
                'updated_at' => '2026-02-16 14:30:35',
            ),
            22 => 
            array (
                'id' => 23,
                'sku' => 'CAM-004',
                'category_id' => 2,
                'brand_id' => 4,
                'is_active' => 1,
                'is_featured' => 0,
                'sort_order' => 59,
                'name' => 'Target Cam-004',
                'text' => 'Descubre los Target Cam-004, una perfecta combinación de estilo y funcionalidad. Fabricado con los mejores materiales para garantizar confort y durabilidad.',
                'price' => '384881.00',
                'list_price' => '481101.25',
                'slug' => 'target-12-cam-004',
                'icon' => NULL,
                'description' => 'Target Cam-004 - Elegante y moderno diseño con materiales de alta calidad. Ideal para cualquier ocasión.',
                'specifications' => NULL,
                'active' => 1,
                'order' => 0,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-16 14:30:35',
                'updated_at' => '2026-02-16 14:30:35',
            ),
            23 => 
            array (
                'id' => 24,
                'sku' => 'CAM-007',
                'category_id' => 3,
                'brand_id' => 3,
                'is_active' => 1,
                'is_featured' => 0,
                'sort_order' => 100,
                'name' => 'Vogue Cam-007',
                'text' => 'Descubre los Vogue Cam-007, una perfecta combinación de estilo y funcionalidad. Fabricado con los mejores materiales para garantizar confort y durabilidad.',
                'price' => '721676.00',
                'list_price' => '902095.00',
                'slug' => 'vogue-13-cam-007',
                'icon' => NULL,
                'description' => 'Vogue Cam-007 - Elegante y moderno diseño con materiales de alta calidad. Ideal para cualquier ocasión.',
                'specifications' => NULL,
                'active' => 1,
                'order' => 0,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-16 14:30:36',
                'updated_at' => '2026-02-16 14:30:36',
            ),
            24 => 
            array (
                'id' => 25,
                'sku' => 'CAM-007',
                'category_id' => 1,
                'brand_id' => 6,
                'is_active' => 1,
                'is_featured' => 0,
                'sort_order' => 75,
                'name' => 'Prada Cam-007',
                'text' => 'Descubre los Prada Cam-007, una perfecta combinación de estilo y funcionalidad. Fabricado con los mejores materiales para garantizar confort y durabilidad.',
                'price' => '913183.00',
                'list_price' => '1141478.75',
                'slug' => 'prada-14-cam-007',
                'icon' => NULL,
                'description' => 'Prada Cam-007 - Elegante y moderno diseño con materiales de alta calidad. Ideal para cualquier ocasión.',
                'specifications' => NULL,
                'active' => 1,
                'order' => 0,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-16 14:30:36',
                'updated_at' => '2026-02-16 14:30:36',
            ),
        ));
        
        
    }
}